# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0005_remove_question_m_majoruse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_m',
            name='age',
        ),
        migrations.RemoveField(
            model_name='question_m',
            name='task',
        ),
        migrations.AddField(
            model_name='question_m',
            name='majoruse',
            field=models.CharField(choices=[('Calling', 'Calling'), ('Photography', 'Photography'), ('Gaming', 'Gaming'), ('Whatsapp', 'Whatsapp'), ('Movie', 'Movie')], default='Calling', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_m',
            name='budget',
            field=models.CharField(default='5000', max_length=100),
        ),
        migrations.AlterField(
            model_name='question_m',
            name='profession',
            field=models.CharField(choices=[('Student', 'Student'), ('Job', 'Job'), ('Business', 'Buisness'), ('Elderly Person', 'Elderly Person')], default='Student', max_length=100),
        ),
    ]
