# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-20 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0006_auto_20180320_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_m',
            name='majoruse',
            field=models.CharField(choices=[('Calling', 'Calling'), ('Photography', 'Photography'), ('Gaming', 'Gaming'), ('Social Media', 'Social Media'), ('Videos & Movies', 'Videos & Movies')], default=['Calling'], max_length=100),
        ),
    ]
